[package]
name = "bplustree3"
version = "0.1.0"
edition = "2024"

[lib]
doctest = false

[features]
default = []
testing = []

[dependencies]

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
rand = "0.8"

[[bench]]
name = "comparison"
harness = false
