name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd python
        pip install -e .[test]
    
    - name: Run fast tests
      run: |
        cd python
        python -m pytest tests/ --ignore=tests/test_c_extension_segfault_fix.py -m "not slow" -x -v
    
    - name: Run selected slow tests (with timeout)
      run: |
        cd python
        echo "Running memory leak test..."
        timeout 3m python -m pytest tests/test_memory_leaks.py::TestMemoryLeaks::test_deleted_values_are_released -v || echo "Memory leak test timed out or failed (non-critical)"
        
        echo "Running small performance benchmark..."
        timeout 2m python -m pytest tests/test_performance_benchmarks.py::TestPerformanceBenchmarks::test_insertion_performance_small -v || echo "Performance test timed out or failed (non-critical)"
        
        echo "Running basic stress test..."
        timeout 2m python -m pytest tests/test_bplus_tree.py::test_many_insertions_maintain_invariants -v || echo "Stress test timed out or failed (non-critical)"
