name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd python
        pip install -e .[test]
    
    - name: Run fast tests
      run: |
        cd python
        python -m pytest tests/ --ignore=tests/test_c_extension_segfault_fix.py -m "not slow" -x -v
    
    - name: Run critical reliability tests
      run: |
        cd python
        echo "Running memory leak test (CRITICAL)..."
        timeout 5m python -m pytest tests/test_memory_leaks.py::TestMemoryLeaks::test_insertion_deletion_cycle_no_leak -v --tb=short
        
        echo "Running performance regression test (CRITICAL)..."
        timeout 3m python -m pytest tests/test_performance_benchmarks.py::TestPerformanceBenchmarks::test_insertion_performance_small -v --tb=short
        
        echo "Running invariant stress test (CRITICAL)..."
        timeout 3m python -m pytest tests/test_bplus_tree.py::test_many_insertions_maintain_invariants -v --tb=short
