name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd python
        pip install -e .[test]
    
    - name: Run fast tests
      run: |
        cd python
        python -m pytest tests/ --ignore=tests/test_c_extension_segfault_fix.py -m "not slow" -x -v
    
    - name: Run selected slow tests (with timeout)
      run: |
        cd python
        timeout 5m python -m pytest tests/test_memory_leaks.py::TestMemoryLeaks::test_deleted_values_are_released -v || echo "Slow test timed out or failed (non-critical)"
