name: Python Tests

on:
  push:
    branches: [main]
    paths:
      - "python/**"
      - ".github/workflows/python-tests.yml"
  pull_request:
    branches: [main]
    paths:
      - "python/**"
      - ".github/workflows/python-tests.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          cd python
          pip install -e .

      - name: Run basic tests
        run: |
          cd python
          python -m pytest tests/test_dictionary_api.py -v

      - name: Test basic functionality
        run: |
          cd python
          python -c "import bplustree; tree = bplustree.BPlusTreeMap(); tree[1] = 'test'; print(f'Success: {tree[1]}'); print(f'Implementation: {bplustree.get_implementation()}')"
