name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Check code formatting
      run: |
        cd rust
        cargo fmt --check
    
    - name: Run clippy
      run: |
        cd rust
        cargo clippy -- -D warnings
    
    - name: Build
      run: |
        cd rust
        cargo build --verbose
    
    - name: Run tests
      run: |
        cd rust
        cargo test --verbose
